
export const LANGUAGES = [
    'English',
    'Spanish',
    'Portuguese',
    'French',
    'Arabic',
    'Urdu',
    'Punjabi',
    'Bengali',
    'Polish',
    'Romanian',
    'Italian',
    'German',
    'Chinese (Mandarin)',
    'Chinese (Cantonese)',
    'Japanese',
    'Russian',
    'Turkish',
    'Farsi',
    'Pashto',
    'Somali',
    'Tigrinya',
    'Albanian',
    'Lithuanian',
    'Latvian',
    'Bulgarian',
    'Hungarian',
    'Greek',
    'Vietnamese',
    'Thai',
    'Korean',
    'Hindi',
    'Gujarati',
    'Tamil',
    'Kurdish (Sorani)',
    'Kurdish (Kurmanji)',
    'Amharic',
    'Yoruba',
    'Igbo',
    'Slovak',
    'Czech'
].sort();
